-- 1. CREATING A NEW DATA BASE NAMED AS EMPLOYEEs_ANALYTICS
CREATE DATABASE Employees_analytics;
-- USING THEDATA BASE NOW 
USE Employees_analytics;

-- 2. now we have to create the table if it doesnot exist(AT FIRST DROPPING THE TABLE IF IT ALREADY EXISTS)
DROP TABLE IF EXISTS Departments;
CREATE TABLE DEPARTMENTS(
	DEPARTMENT_ID Int auto_increment primary key, -- COLUMN NAME, DATA TYPE AND CONSTRAINTS 
    DEPARTMENT_NAME VARCHAR(100) NOT NULL -- THE NAME OF THE DEPARTMENT CANNOT BE NULL.
    
);

 
-- 3. NOW WE HAVE CREATED THE TABLE FOR THE DEPARTMENT.
-- NOW WE ALSO NEED THE EMPLOYEES IN THAT DEPARTEMNTS. 
-- SO CREATING THE TABLE FOR VARIOUS EMPLOYEES TOO.
DROP TABLE IF EXISTS Employees;
CREATE TABLE Employees(
	EMPLOYEE_ID INT auto_increment PRIMARY KEY,
    DEPARTMENT_ID INT,
    EMPLOYEE_FIRST_NAME VARCHAR(200) NOT NULL,
	EMPLOYEE_LAST_NAME VARCHAR(200) NOT NULL,
    GENDER ENUM('MALE','FEMALE','OTHER'),
    HIRED_DATE date,
    EMPLOYEE_MAIL VARCHAR(200) UNIQUE NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);
-- 4. now we need the prompts for the salaries too. 
DROP TABLE IF EXISTS SALARIES;
CREATE TABLE SALARIES(
	SALARY_ID INT auto_increment primary KEY,
    EMPLOYEE_ID INT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    SALARY DECIMAL (10,2),
    EFFECTIVE_DATE DATE
);
