USE EMPLOYEES_ANALYTICS;

-- NOW WE ARE EXPLORING AND ANALYZING THE DATA WE HAVE COLLECTED SO FAR. 
-- 1. Average salary by department 
SELECT 
    d.DEPARTMENT_NAME, ROUND(AVG(s.SALARY), 2) AS AVG_SALARY
FROM
    Employees e
        JOIN
    Departments d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
        JOIN
    Salaries s ON e.EMPLOYEE_ID = s.EMPLOYEE_ID
GROUP BY d.DEPARTMENT_NAME
ORDER BY AVG_SALARY DESC;  -- ORDERING BY AVG SALARY IN DESCENDING ORDER. 

-- NOTE; Departments.DEPARTMENT_NAME
-- Employees.DEPARTMENT_ID
-- Salaries.SALARY
-- IF WE WRITE LIEK THIS EVERYTIME IT BECOMES NOT SO CONVENIENT SO USING THE FORMAT BELOW

-- d.DEPARTMENT_NAME
-- e.DEPARTMENT_ID
-- s.SALARY
-- Much shorter and cleaner.

-- e. = Employees table
-- d. = Departments table
-- s. = Salaries table
-- These are just like nicknames 

-- SO THE RESULT SHOWS WHICH DEPARTMENT EARNS THE MOST ON AVAERAGE. 


-- 2. NOW I WANT TO KNOW THE HIGHEST PAID EMPLOYEE (TOP 10) 
SELECT 
	e.EMPLOYEE_FIRST_NAME, -- EMPLOYEE.EMPLOYEE_FIRST_NAME. SELECTING EMPLOYEE'S FIRST NAME FROM EMPLOYEE TABLE.  
    e.EMPLOYEE_LAST_NAME,  -- EMPLOYEE LAST NAME
    S.SALARY -- THEIR RESPECTIVE SALARY
FROM EMPLOYEES e 
JOIN SALARIES S
	ON e.EMPLOYEE_ID=S.EMPLOYEE_ID -- CONNECTING SALARIES TO THE CORRECT EMPLOYEE
ORDER BY s.SALARY DESC    -- ORDERING IN DESCENDING ORDER. 
LIMIT 10;  -- THIS SHOWS THE TOP 10 HIGHEST PAID EMPLOYEE OF THE COMPANY.



-- 3.WE ALSO NEED TO KNOW HOW MUCH PEOPLE ARE IN EACH DEPARTMENTS  
SELECT 
	d.DEPARTMENT_NAME,   -- SLECTING THE DIFFERENT DEPARTMENTS. 
    COUNT(*) AS TOTAL_NUMBER_OF_EMPLOYEES -- NUMBER OF EMPLOYEES IN THAT DEPARTMENT
FROM EMPLOYEES e
JOIN DEPARTMENTS d
	ON e.DEPARTMENT_ID=d.DEPARTMENT_ID -- CONNECTING EMPLOYEES TO THIER DEPARTMENTS 
GROUP BY d.DEPARTMENT_NAME        --  COUNTING EACH DEPARTMENT SEPARATELY
ORDER BY TOTAL_NUMBER_OF_EMPLOYEES DESC;    -- ORDERING THE DEPARTMENT WOITH MOST ERMPLOYEES AT FIRST AND IN DESCENDING ORDER.
-- THIS SHOWS HOW MANY EMPLOYEES EACH DEPARTMENT HAS. 
 

    

-- 4. DIFFERENCE IN PAY AMONG THE GENDERS.
SELECT 
	e.GENDER,     -- SLECTING THE GENDER FROM THE EMPLOYEES TABLE 
    ROUND (AVG(s.SALARY),2) AS AVG_SALARY -- CALCULATE TEH AVERAGE OF THE SALARY AND ROUND TO DECIMAL .2 
FROM EMPLOYEES e 
JOIN SALARIES s 
	on e.employee_id=s.employee_id  -- cponnecting the salaries with the employees
GROUP BY e.gender; --  calculate teh average salary for each gender separately


-- 5. salary distribution
SELECT 
	MIN(s.SALARY) AS MIN_SALARY, -- LOWEST SALARY IN THE COMPANY
    MAX(s.SALARY) AS MAx_salary,  -- MAX SALARY IN THE COMPANY
    ROUND(AVG(s.SALARY),2) AS AVG_SALARY
FROM SALARIES s;





-- 6. Highest Paid Employee in Each Department
SELECT 
	d.DEPARTMENT_NAME,
    e.EMPLOYEE_FIRST_NAME,
    e.EMPLOYEE_LAST_NAME,
    S.SALARY -- THIER SALARY 
FROM EMPLOYEES e
JOIN SALARIES s
	ON e.EMPLOYEE_ID = s.EMPLOYEE_ID   -- ConnectING THE  EMPLOYEE TO THIER SALARY. 
JOIN Departments d 
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID  -- CONNECTING EMPLOYEE TO THIER DEPARTMENT 
WHERE (d.DEPARTMENT_ID, s.SALARY) IN (
    SELECT DEPARTMENT_ID, MAX(SALARY)  -- FOR EACH DEPARTMENT FINDING THE HIGHEST SALARY
    FROM Employees e2
    JOIN Salaries s2 ON e2.EMPLOYEE_ID = s2.EMPLOYEE_ID
    GROUP BY DEPARTMENT_ID             -- DOING THIS SEPARATELY FOR EACH DEPARTMENT
);


-- 7. Average Salary by Gender in Each Department
SELECT 
    d.DEPARTMENT_NAME,                 -- NAME OF THE DEPARTMENT
    e.GENDER,                          -- GENDER OF THE EMPLOYEES IN THAT DEPARTMENT
    ROUND(AVG(s.SALARY), 2) AS AVG_SALARY  -- AAVERAGE SALARY FOR THAT GENDER IN THAT DEPARTMENT
FROM Employees e
JOIN Salaries s 
    ON e.EMPLOYEE_ID = s.EMPLOYEE_ID   --  CONNECTING THE SALARIES TO THE EMPLOYUEES.
JOIN Departments d 
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID  -- CONNECTING EMPLOYEES TO THE DEPARTMENT
GROUP BY d.DEPARTMENT_NAME, e.GENDER   
ORDER BY d.DEPARTMENT_NAME, e.GENDER; 
 


